// Settings section components
export { default as TaskTypesSection } from './TaskTypesSection.vue'
export { default as TaskTypeCard } from './TaskTypeCard.vue'
export { default as PeopleSection } from './PeopleSection.vue'
export { default as EmailsSection } from './EmailsSection.vue'
export { default as FilesSection } from './FilesSection.vue'
export { default as CostGroupsSection } from './CostGroupsSection.vue'
export { default as LocationsSection } from './LocationsSection.vue'
export { default as AppearanceSection } from './AppearanceSection.vue'
export { default as GeneralSection } from './GeneralSection.vue'
export { default as DisplaySection } from './DisplaySection.vue'
export { default as KeyBindingsSection } from './KeyBindingsSection.vue'
export { default as LinkHandlingSection } from './LinkHandlingSection.vue'
export { default as PlaceholderSection } from './PlaceholderSection.vue'
export { default as SyncFiltersSection } from './SyncFiltersSection.vue'

